import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-container': 'var(--color-tertiary-container)',
        'outline-variant': 'var(--color-outline-variant)',
        'error-container': 'var(--color-error-container)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'secondary': 'var(--color-secondary)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'error': 'var(--color-error)',
        'outline': 'var(--color-outline)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'surface-tint': 'var(--color-surface-tint)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'surface-container': 'var(--color-surface-container)',
        'on-primary': 'var(--color-on-primary)',
        'on-error': 'var(--color-on-error)',
        'on-background': 'var(--color-on-background)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'tertiary': 'var(--color-tertiary)',
        'surface-bright': 'var(--color-surface-bright)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'on-surface': 'var(--color-on-surface)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'surface': 'var(--color-surface)',
        'primary-container': 'var(--color-primary-container)',
        'secondary-container': 'var(--color-secondary-container)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'background': 'var(--color-background)',
        'on-error-container': 'var(--color-on-error-container)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'surface-variant': 'var(--color-surface-variant)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'primary': 'var(--color-primary)',
        'surface-dim': 'var(--color-surface-dim)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'on-secondary': 'var(--color-on-secondary)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        // ── EPC Rating colours (Official UK Government scale) ────────────
        'epc-a': '#008037',
        'epc-b': '#52AE32',
        'epc-c': '#8CBD1B',
        'epc-d': '#F5DB1F',
        'epc-e': '#F58220',
        'epc-f': '#ED732E',
        'epc-g': '#E02621',
      },
      spacing: {
        'xs':            '8px',
        'sm':            '12px',
        'md':            '16px',
        'lg':            '24px',
        'xl':            '32px',
        'gutter':        '20px',
        'base':          '4px',
        'container-max': '1440px',
        'sidebar':       '240px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm:      '0.125rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'data-mono': ['JetBrains Mono', 'monospace'],
        'display-lg': ['Geist', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'display-lg-mobile': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'body-sm': ['Inter', 'sans-serif'],
        sans:  ['Inter', 'sans-serif'],
        mono:  ['JetBrains Mono', 'monospace'],
        geist: ['Geist', 'sans-serif'],
      },
      fontSize: {
        'label-caps':         ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md':            ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg':            ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md':        ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'display-lg-mobile':  ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg':         ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'data-mono':          ['14px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-lg':        ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md':           ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-sm':            ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
      boxShadow: {
        'card':   '0px 2px 4px rgba(30, 41, 59, 0.05)',
        'modal':  '0px 10px 15px rgba(30, 41, 59, 0.1)',
        'glow-primary': '0 0 0 3px rgba(9, 20, 38, 0.15)',
      },
      animation: {
        'ping-slow': 'ping 2s cubic-bezier(0, 0, 0.2, 1) infinite',
      },
    },
  },
  plugins: [],
}

export default config
