import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // ── Surface tokens (Light) ──────────────────────────────────────
        'surface':                   '#f8f9ff',
        'surface-dim':               '#cbdbf5',
        'surface-bright':            '#f8f9ff',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#eff4ff',
        'surface-container':         '#e5eeff',
        'surface-container-high':    '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-variant':           '#d3e4fe',
        'surface-tint':              '#545f73',
        'on-surface':                '#0b1c30',
        'on-surface-variant':        '#45474c',
        'inverse-surface':           '#213145',
        'inverse-on-surface':        '#eaf1ff',
        // ── Primary ──────────────────────────────────────────────────────
        'primary':                   '#091426',
        'on-primary':                '#ffffff',
        'primary-container':         '#1e293b',
        'on-primary-container':      '#8590a6',
        'primary-fixed':             '#d8e3fb',
        'primary-fixed-dim':         '#bcc7de',
        'on-primary-fixed':          '#111c2d',
        'on-primary-fixed-variant':  '#3c475a',
        'inverse-primary':           '#bcc7de',
        // ── Secondary ────────────────────────────────────────────────────
        'secondary':                 '#515f74',
        'on-secondary':              '#ffffff',
        'secondary-container':       '#d5e3fd',
        'on-secondary-container':    '#57657b',
        'secondary-fixed':           '#d5e3fd',
        'secondary-fixed-dim':       '#b9c7e0',
        'on-secondary-fixed':        '#0d1c2f',
        'on-secondary-fixed-variant':'#3a485c',
        // ── Tertiary ─────────────────────────────────────────────────────
        'tertiary':                  '#1e1200',
        'on-tertiary':               '#ffffff',
        'tertiary-container':        '#35260c',
        'on-tertiary-container':     '#a38c6a',
        'tertiary-fixed':            '#fadfb8',
        'tertiary-fixed-dim':        '#ddc39d',
        'on-tertiary-fixed':         '#271902',
        'on-tertiary-fixed-variant': '#564427',
        // ── Error ────────────────────────────────────────────────────────
        'error':                     '#ba1a1a',
        'on-error':                  '#ffffff',
        'error-container':           '#ffdad6',
        'on-error-container':        '#93000a',
        // ── Outline ──────────────────────────────────────────────────────
        'outline':                   '#75777d',
        'outline-variant':           '#c5c6cd',
        // ── Background ───────────────────────────────────────────────────
        'background':                '#f8f9ff',
        'on-background':             '#0b1c30',
        // ── Dark surface tokens ──────────────────────────────────────────
        'dark-surface':                   '#0b1326',
        'dark-surface-dim':               '#0b1326',
        'dark-surface-bright':            '#31394d',
        'dark-surface-container-lowest':  '#060e20',
        'dark-surface-container-low':     '#131b2e',
        'dark-surface-container':         '#171f33',
        'dark-surface-container-high':    '#222a3d',
        'dark-surface-container-highest': '#2d3449',
        'dark-on-surface':                '#dae2fd',
        'dark-on-surface-variant':        '#bdc8d1',
        'dark-primary':                   '#8ed5ff',
        'dark-on-primary':                '#00354a',
        'dark-primary-container':         '#38bdf8',
        'dark-on-primary-container':      '#004965',
        'dark-outline-variant':           '#3e484f',
        'dark-outline':                   '#87929a',
        'dark-background':                '#0b1326',
        'dark-error':                     '#ffb4ab',
        'dark-error-container':           '#93000a',
        // ── EPC Rating colours (Official UK Government scale) ────────────
        'epc-a': '#008037',
        'epc-b': '#52AE32',
        'epc-c': '#8CBD1B',
        'epc-d': '#F5DB1F',
        'epc-e': '#F58220',
        'epc-f': '#ED732E',
        'epc-g': '#E02621',
      },
      spacing: {
        'xs':            '8px',
        'sm':            '12px',
        'md':            '16px',
        'lg':            '24px',
        'xl':            '32px',
        'gutter':        '20px',
        'base':          '4px',
        'container-max': '1440px',
        'sidebar':       '240px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm:      '0.125rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      fontFamily: {
        sans:  ['Inter', 'sans-serif'],
        mono:  ['JetBrains Mono', 'monospace'],
        geist: ['Geist', 'sans-serif'],
      },
      fontSize: {
        'label-caps':         ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md':            ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg':            ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md':        ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'display-lg-mobile':  ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg':         ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      boxShadow: {
        'card':   '0px 2px 4px rgba(30, 41, 59, 0.05)',
        'modal':  '0px 10px 15px rgba(30, 41, 59, 0.1)',
        'glow-primary': '0 0 0 3px rgba(9, 20, 38, 0.15)',
      },
      animation: {
        'ping-slow': 'ping 2s cubic-bezier(0, 0, 0.2, 1) infinite',
      },
    },
  },
  plugins: [],
}

export default config
